FROM python:3.9-slim

RUN apt-get update && apt-get install -y gcc make

WORKDIR /app

COPY . /app/

RUN gcc -o vm /app/vm.c -s
RUN python3 /app/lc3-asm/lc3.py /app/chall.asm
RUN mkdir -p /output
RUN cp /app/vm /app/chall-out.obj /output/

# Lancer le conteneur et laisser tourner
CMD ["tail", "-f", "/dev/null"]
