version: '3'
services:
  colour-picker:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8001:80
    environment:
      - PORT=80
      - DEBUG=False
    mem_limit: 512m
    cpu_count: 1